[package]
name = "key_remapper"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Console"
] }

rand      = "0.8"
once_cell = "1.19"